### Numpy Array

In [16]:
import numpy as np

creating an array from a list

In [17]:
array_1=np.array([40,42,43])
print("1D array:",array_1)
array_2= np.array([[21,22,23],[6,7,8]])
print("2D array:",array_2)


1D array: [40 42 43]
2D array: [[21 22 23]
 [ 6  7  8]]


In [18]:
list_1=[1,2,3]
print("multiplication on list", list_1*2)

array_3= np.array([1,2,3])
print("multiplication on array:", array_3*2)

import time
start= time.time()
list_1=[i*2 for i in range(1000000)]
print("\n list operation time:", time.time()-start)

start= time.time()
np_array = np.arange(1000000)
print("\n Numpy operation time:", time.time()- start)

multiplication on list [1, 2, 3, 1, 2, 3]
multiplication on array: [2 4 6]

 list operation time: 0.03533291816711426

 Numpy operation time: 0.0015780925750732422


### creating an array from scratch

In [15]:
zeroes= np.zeros((3,4))
print("zeros array:\n", zeroes)

ones= np.ones((3,4))
print("ones array: \n", ones)

full_method= np.full((3,4),7)
print("full array:\n", full_method)

random= np.random.random((2,2))
print("random array:\n", random)

sequence= np.arange(0,11,2)
print("sequence array:", sequence)



zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array:
 [[0.37783201 0.88811371]
 [0.05177184 0.05241536]]
sequence array: [ 0  2  4  6  8 10]


## vector,matrix and tensor

In [21]:
vector= np.array([1,2,3])
print("vector array:", vector)

matrix= np.array([[1,2,3],[3,4,5]])
print("matrix array:\n", matrix)

tensor= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor array:\n", tensor)




vector array: [1 2 3]
matrix array:
 [[1 2 3]
 [3 4 5]]
tensor array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
